name: Fetch Sklavenitis
on:
  workflow_dispatch:
  schedule:
    # UTC Time.
    - cron: "0 22 * * Tue,Thu,Sat"
jobs:
  fetch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install requirements
        shell: bash
        run:
          pip install -r requirements.txt
      - name: Scrape
        shell: bash
        run:
          scrapy runspider sklavenitis.py  -s DOWNLOAD_DELAY=1.5 --output "data/sklavenitis-$(date +%Y-%m-%d-%H-%M).json"
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "New data"
          add: 'data/*'
